package fact_test

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/OpenAgriNet/discovery-service/src/platform/telemetry/fact"
)

// update rewrites the golden file instead of comparing against it.
//
// telemetry-seam.md 5g says "generated by go:generate". This is that, with the
// generator living in the test rather than in a second main package. The
// directive below invokes it, so `go generate ./...` still works and there is
// no separate binary whose own correctness nobody checks. The difference the
// doc cares about — a registry edit shows up as a reviewable diff in the PR
// that makes it — is unaffected.
//
//go:generate go test . -run TestTheGoldenFileMatchesTheRegistry -update
var update = flag.Bool("update", false, "rewrite testdata/registry.golden.txt")

const goldenPath = "testdata/registry.golden.txt"

// TestTheGoldenFileMatchesTheRegistry is the reviewability guard, and it is the
// only test here that asserts nothing about correctness.
//
// Every other test in this package checks that a row is self-consistent. None of
// them can check that a row is what somebody INTENDED — that beckn.action is
// Public rather than LocalOnly, that result.catalog_count is Unbounded. Those
// are judgements, and the only mechanism that catches a wrong one is a human
// reading the change. This file is what puts the change in front of them: a
// one-character edit to a Visibility deep inside a 47-row table is invisible in
// a diff of registry.go and unmissable in a diff of this.
func TestTheGoldenFileMatchesTheRegistry(t *testing.T) {
	rendered := render()

	if *update {
		if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
			t.Fatalf("create the testdata directory: %v", err)
		}
		if err := os.WriteFile(goldenPath, []byte(rendered), 0o644); err != nil {
			t.Fatalf("write the golden file: %v", err)
		}
		t.Logf("wrote %s", goldenPath)
		return
	}

	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read the golden file: %v\n"+
			"        Regenerate it with: go test ./src/platform/telemetry/fact -update", err)
	}

	if string(want) != rendered {
		t.Errorf("the registry and %s disagree.\n"+
			"        If the registry change was intended, regenerate:\n"+
			"            go test ./src/platform/telemetry/fact -update\n"+
			"        and put the resulting diff in the same commit — that diff IS the\n"+
			"        review. If it was not intended, the registry is what to fix.\n\n%s",
			goldenPath, firstDifference(string(want), rendered))
	}
}

// render writes one line per row, and a header naming every field of Definition
// in declaration order.
//
// The header is not decoration. Rows print only their non-zero fields, which
// keeps a line readable, and that alone would make ADDING a field to Definition
// invisible in the golden whenever the new field is unset on all 47 rows — which
// is exactly the state a field is in on the commit that introduces it. The
// header changes then, so the diff exists.
func render() string {
	var out strings.Builder

	definitionType := reflect.TypeOf(fact.Definition{})
	fields := make([]string, 0, definitionType.NumField())
	for index := range definitionType.NumField() {
		fields = append(fields, definitionType.Field(index).Name)
	}

	out.WriteString("# Generated by go test ./src/platform/telemetry/fact -update. Do not hand-edit.\n")
	out.WriteString("# One line per fact.Key, in key order. Fields at their zero value are omitted.\n")
	out.WriteString("# Definition fields: " + strings.Join(fields, " ") + "\n")

	for key, def := range fact.All() {
		out.WriteString(fmt.Sprintf("%3d %s\n", int(key), renderRow(def, fields)))
	}
	return out.String()
}

func renderRow(def fact.Definition, fields []string) string {
	value := reflect.ValueOf(def)

	parts := make([]string, 0, len(fields))
	for index, name := range fields {
		field := value.Field(index)
		if field.IsZero() {
			continue
		}
		parts = append(parts, name+"="+renderValue(field))
	}
	return strings.Join(parts, " ")
}

// renderValue prefers a Stringer, so the golden reads Bounded rather than 1 and
// a reviewer can see what changed without holding the const blocks in their head.
func renderValue(field reflect.Value) string {
	if stringer, ok := field.Interface().(fmt.Stringer); ok {
		return stringer.String()
	}
	if field.Kind() == reflect.Slice {
		entries := make([]string, field.Len())
		for index := range field.Len() {
			entries[index] = renderValue(field.Index(index))
		}
		return "[" + strings.Join(entries, ",") + "]"
	}
	if field.Kind() == reflect.Struct {
		return fmt.Sprintf("%+v", field.Interface())
	}
	return fmt.Sprintf("%v", field.Interface())
}

// firstDifference reports the first line that differs, because a whole-file diff
// of 47 rows in a Go failure message is something nobody reads to the end of.
func firstDifference(want, got string) string {
	wantLines, gotLines := strings.Split(want, "\n"), strings.Split(got, "\n")

	for index := range max(len(wantLines), len(gotLines)) {
		wantLine, gotLine := at(wantLines, index), at(gotLines, index)
		if wantLine != gotLine {
			return fmt.Sprintf("        first difference, line %d:\n"+
				"        golden:   %s\n"+
				"        registry: %s", index+1, wantLine, gotLine)
		}
	}
	return "        the files differ but no line does; check the trailing newline"
}

func at(lines []string, index int) string {
	if index >= len(lines) {
		return "(end of file)"
	}
	return lines[index]
}
