package geo_test

import (
	"encoding/json"
	"math"
	"testing"

	"github.com/OpenAgriNet/discovery-service/src/domain"
	"github.com/OpenAgriNet/discovery-service/src/indexing/geo"
)

var (
	bengaluru = domain.GeoPoint{Lat: 12.9716, Lon: 77.5946}
	chennai   = domain.GeoPoint{Lat: 13.0827, Lon: 80.2707}
	delhi     = domain.GeoPoint{Lat: 28.6139, Lon: 77.2090}
)

// point builds a stored Point geometry the way the walker would.
func point(at domain.GeoPoint) domain.Geometry {
	body, err := json.Marshal(map[string]any{
		"type":        "Point",
		"coordinates": []float64{at.Lon, at.Lat},
	})
	if err != nil {
		panic(err)
	}
	return domain.Geometry{Type: "Point", GeoJSON: body}
}

func polygonAround(at domain.GeoPoint) domain.Geometry {
	const side = 0.05
	ring := [][]float64{
		{at.Lon - side, at.Lat - side},
		{at.Lon + side, at.Lat - side},
		{at.Lon + side, at.Lat + side},
		{at.Lon - side, at.Lat + side},
		{at.Lon - side, at.Lat - side},
	}
	body, err := json.Marshal(map[string]any{"type": "Polygon", "coordinates": [][][]float64{ring}})
	if err != nil {
		panic(err)
	}
	return domain.Geometry{Type: "Polygon", GeoJSON: body}
}

// closeEnough compares metres. The tolerance is a millimetre: the SQL twin
// evaluates the same expression in the same order, so anything larger would let
// a genuinely different formula pass.
func closeEnough(got, want float64) bool {
	return math.Abs(got-want) < 0.001
}

// The expected values are computed from the formula the SQL twin spells out —
// 2 * 6371008.8 * asin(sqrt(...)) — not read back from this implementation. A
// table generated by the code it checks pins nothing.
func TestHaversineMatchesTheFormulaTheSQLTwinUses(t *testing.T) {
	cases := []struct {
		name     string
		from, to domain.GeoPoint
		want     float64
	}{
		{"bengaluru to chennai", bengaluru, chennai, 290172.42575573263},
		{"bengaluru to delhi", bengaluru, delhi, 1739804.5050131553},
		{"one degree of latitude at the equator", domain.GeoPoint{}, domain.GeoPoint{Lat: 1}, 111195.0802335329},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			if got := geo.HaversineM(testCase.from, testCase.to); !closeEnough(got, testCase.want) {
				t.Errorf("HaversineM = %.6f m, want %.6f m", got, testCase.want)
			}
		})
	}
}

func TestAPointIsNoDistanceFromItself(t *testing.T) {
	if got := geo.HaversineM(bengaluru, bengaluru); got != 0 {
		t.Errorf("HaversineM to itself = %v, want 0", got)
	}
}

func TestDistanceIsSymmetric(t *testing.T) {
	there, back := geo.HaversineM(bengaluru, chennai), geo.HaversineM(chennai, bengaluru)
	if !closeEnough(there, back) {
		t.Errorf("HaversineM is not symmetric: %v vs %v", there, back)
	}
}

// The clamp, and the reason the SQL carries `least(1, ...)`. Floating-point
// overshoot puts asin's argument at 1+1e-16 for antipodal points, which is a
// hard error in PostgreSQL and a NaN here.
func TestAntipodalPointsAreHalfTheWayAround(t *testing.T) {
	got := geo.HaversineM(domain.GeoPoint{}, domain.GeoPoint{Lon: 180})
	if math.IsNaN(got) {
		t.Fatal("HaversineM returned NaN on antipodal points; the clamp is missing")
	}
	if !closeEnough(got, 20015114.442035925) {
		t.Errorf("HaversineM antipodal = %.6f m, want 20015114.442036 m", got)
	}
}

func TestNearestGeometryReturnsTheNearerPoint(t *testing.T) {
	metres, ok := geo.NearestGeometryM(bengaluru, []domain.Geometry{point(delhi), point(chennai)})
	if !ok {
		t.Fatal("NearestGeometryM declined a set containing two Points")
	}
	if !closeEnough(metres, 290172.42575573263) {
		t.Errorf("nearest = %.3f m, want the Chennai distance 290172.426 m", metres)
	}
}

// ok == false means "no refinement applies", NOT "no match". A caller reading it
// as a miss drops every resource whose only geometry is a Polygon from an
// S_DWITHIN — which is the regression this design corrected, so it is asserted
// directly rather than left to the caller's test.
func TestNearestGeometryDeclinesWhenNothingIsAPoint(t *testing.T) {
	metres, ok := geo.NearestGeometryM(bengaluru, []domain.Geometry{polygonAround(chennai)})
	if ok {
		t.Fatalf("NearestGeometryM answered %v m for a set with no Point", metres)
	}
	if metres != 0 {
		t.Errorf("a declined refinement returned %v m; it must carry no distance at all", metres)
	}
}

func TestNearestGeometryIgnoresNonPointsBesideAPoint(t *testing.T) {
	metres, ok := geo.NearestGeometryM(bengaluru, []domain.Geometry{polygonAround(bengaluru), point(chennai)})
	if !ok {
		t.Fatal("NearestGeometryM declined a set containing one Point")
	}
	if !closeEnough(metres, 290172.42575573263) {
		t.Errorf("nearest = %.3f m, want the Chennai distance — the Polygon must not participate", metres)
	}
}

func TestNearestGeometryDeclinesAnEmptySet(t *testing.T) {
	if _, ok := geo.NearestGeometryM(bengaluru, nil); ok {
		t.Error("NearestGeometryM answered for an empty set")
	}
}

// A Point whose coordinates cannot be read is not a Point for this purpose. It
// must not read as distance zero, which would make an unparseable geometry the
// nearest thing to every query.
func TestAnUnreadablePointIsNotARefinement(t *testing.T) {
	broken := domain.Geometry{Type: "Point", GeoJSON: json.RawMessage(`{"type":"Point","coordinates":[]}`)}
	if metres, ok := geo.NearestGeometryM(bengaluru, []domain.Geometry{broken}); ok {
		t.Errorf("NearestGeometryM answered %v m for a Point with no coordinates", metres)
	}
}
